name: Deploy (Latest) Whitelist Application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build Environment
        run: |
          docker pull cdrx/pyinstaller-windows

      - name: Build Windows executable
        run: |
          docker run --rm -v "$(pwd):/src/" cdrx/pyinstaller-windows "pyinstaller --onefile whitelist.py"

      - name: List dist directory
        run: |
          ls -al dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-python-app
          path: dist/whitelist.exe
          if-no-files-found: warn
