name: Deploy (Latest) Whitelist Application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32

      - name: Download Windows Python
        run: |
          mkdir -p ~/.wine/drive_c/Python
          cd ~/.wine/drive_c/Python
          wget https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe
          wine python-3.8.0.exe /quiet InstallAllUsers=1 PrependPath=1

      - name: Install PyInstaller for Windows
        run: |
          wine ~/.wine/drive_c/Python/python.exe -m pip install pyinstaller

      - name: Build Windows executable
        run: |
          wine ~/.wine/drive_c/Python/python.exe -m PyInstaller --onefile whitelist.py

      - name: List dist directory
        run: |
          ls -al dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ReforgerWhitelist
          path: dist/whitelist.exe
          if-no-files-found: warn
