name: Build Latest

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine64 wine32

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Build executable
      run: |
        docker run --rm -v "$(pwd):/src/" cdrx/pyinstaller-windows "pyinstaller --onefile whitelist.py"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ReforgerWhitelist
        path: dist/whitelist.exe
