name: Deploy (Latest) Whitelist Application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller --onefile whitelist.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReforgerWhitelist
          path: dist/whitelist.exe
          if-no-files-found: warn
